import { PrismaClient, Mood, Privacy, TagCategory } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { faker } from '@faker-js/faker';

const prisma = new PrismaClient();

const moods = Object.values(Mood);
const privacyOptions = Object.values(Privacy);
const tagCategories = Object.values(TagCategory);

async function main() {
  console.log('Starting database seeding...');

  // Create test users
  const users = await Promise.all([
    createUser('test@example.com', 'testuser', 'Test123!'),
    createUser('john@example.com', 'johndoe', 'Test123!'),
    createUser('jane@example.com', 'janedoe', 'Test123!'),
  ]);

  console.log(`Created ${users.length} users`);

  // Create entries and tags for each user
  for (const user of users) {
    // Create tags
    const tags = await createTagsForUser(user.id);
    console.log(`Created ${tags.length} tags for user ${user.username}`);

    // Create entries
    const entries = await createEntriesForUser(user.id, tags);
    console.log(`Created ${entries.length} entries for user ${user.username}`);

    // Create user settings
    await createUserSettings(user.id);
  }

  // Create some public entries for social features
  await createPublicEntries(users[0].id);

  console.log('Database seeding completed!');
}

async function createUser(email: string, username: string, password: string) {
  const hashedPassword = await bcrypt.hash(password, 10);
  
  return prisma.user.upsert({
    where: { email },
    update: {},
    create: {
      email,
      username,
      password: hashedPassword,
      avatar: faker.image.avatar(),
    },
  });
}

async function createTagsForUser(userId: string) {
  const tagNames = [
    { name: 'work', category: 'TOPIC' as TagCategory, color: '#FF6B6B' },
    { name: 'personal', category: 'TOPIC' as TagCategory, color: '#4ECDC4' },
    { name: 'travel', category: 'ACTIVITY' as TagCategory, color: '#45B7D1' },
    { name: 'family', category: 'PERSON' as TagCategory, color: '#96CEB4' },
    { name: 'health', category: 'TOPIC' as TagCategory, color: '#FFEAA7' },
    { name: 'goals', category: 'TOPIC' as TagCategory, color: '#DDA0DD' },
    { name: 'meditation', category: 'ACTIVITY' as TagCategory, color: '#98D8C8' },
    { name: 'exercise', category: 'ACTIVITY' as TagCategory, color: '#F7DC6F' },
    { name: 'reading', category: 'ACTIVITY' as TagCategory, color: '#BB8FCE' },
    { name: 'cooking', category: 'ACTIVITY' as TagCategory, color: '#85C1E2' },
  ];

  const tags = await Promise.all(
    tagNames.map(tag =>
      prisma.tag.create({
        data: {
          name: tag.name,
          category: tag.category,
          color: tag.color,
          userId,
        },
      })
    )
  );

  return tags;
}

async function createEntriesForUser(userId: string, tags: any[]) {
  const entries = [];
  const numberOfEntries = faker.number.int({ min: 20, max: 50 });

  for (let i = 0; i < numberOfEntries; i++) {
    const createdAt = faker.date.between({
      from: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000), // 90 days ago
      to: new Date(),
    });

    const content = generateEntryContent();
    const wordCount = content.split(/\s+/).length;

    const entry = await prisma.entry.create({
      data: {
        userId,
        title: faker.lorem.sentence({ min: 3, max: 8 }),
        content,
        mood: faker.helpers.arrayElement(moods),
        privacy: faker.helpers.arrayElement(privacyOptions),
        location: faker.helpers.maybe(() => faker.location.city(), { probability: 0.3 }),
        weather: faker.helpers.maybe(() => 
          faker.helpers.arrayElement(['sunny', 'cloudy', 'rainy', 'snowy', 'windy']), 
          { probability: 0.3 }
        ),
        wordCount,
        isFavorite: faker.datatype.boolean({ probability: 0.2 }),
        createdAt,
        updatedAt: createdAt,
      },
    });

    // Add random tags to entry
    const numberOfTags = faker.number.int({ min: 1, max: 4 });
    const selectedTags = faker.helpers.arrayElements(tags, numberOfTags);

    for (const tag of selectedTags) {
      await prisma.entryTag.create({
        data: {
          entryId: entry.id,
          tagId: tag.id,
          confidence: faker.number.float({ min: 0.7, max: 1.0, precision: 0.01 }),
          autoGenerated: faker.datatype.boolean({ probability: 0.3 }),
        },
      });
    }

    entries.push(entry);
  }

  return entries;
}

async function createUserSettings(userId: string) {
  return prisma.userSettings.create({
    data: {
      userId,
      theme: faker.helpers.arrayElement(['light', 'dark', 'auto']),
      defaultPrivacy: faker.helpers.arrayElement(privacyOptions),
      emailNotifications: faker.datatype.boolean(),
      dailyReminder: faker.datatype.boolean({ probability: 0.4 }),
      reminderTime: faker.helpers.maybe(() => {
        const hour = faker.number.int({ min: 6, max: 22 });
        const minute = faker.number.int({ min: 0, max: 59 });
        return `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
      }, { probability: 0.4 }),
      language: faker.helpers.arrayElement(['en', 'es', 'fr', 'de', 'it']),
      timezone: faker.helpers.arrayElement([
        'UTC',
        'America/New_York',
        'America/Los_Angeles',
        'Europe/London',
        'Europe/Paris',
        'Asia/Tokyo',
      ]),
    },
  });
}

async function createPublicEntries(userId: string) {
  const publicEntries = [];
  
  for (let i = 0; i < 5; i++) {
    const entry = await prisma.entry.create({
      data: {
        userId,
        title: `Public Entry: ${faker.lorem.sentence({ min: 3, max: 8 })}`,
        content: generateEntryContent(),
        mood: faker.helpers.arrayElement(moods),
        privacy: 'PUBLIC',
        wordCount: faker.number.int({ min: 100, max: 500 }),
        isFavorite: faker.datatype.boolean({ probability: 0.3 }),
      },
    });
    publicEntries.push(entry);
  }

  return publicEntries;
}

function generateEntryContent(): string {
  const paragraphs = faker.number.int({ min: 2, max: 5 });
  const content = [];

  for (let i = 0; i < paragraphs; i++) {
    content.push(faker.lorem.paragraph({ min: 3, max: 8 }));
  }

  // Add some variety to content
  if (faker.datatype.boolean({ probability: 0.3 })) {
    content.push(`Today's highlights:\n- ${faker.lorem.sentence()}\n- ${faker.lorem.sentence()}\n- ${faker.lorem.sentence()}`);
  }

  if (faker.datatype.boolean({ probability: 0.2 })) {
    content.push(`Gratitude: ${faker.lorem.sentence()}`);
  }

  return content.join('\n\n');
}

// Run the seed function
main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });