import { PrismaClient, TagCategory, Tag, EntryTag } from '@prisma/client';
import TagService from '../src/services/tagService';

// Mock Prisma
jest.mock('@prisma/client', () => {
  const mockPrismaClient = {
    tag: {
      findUnique: jest.fn(),
      findMany: jest.fn(),
      findFirst: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
      delete: jest.fn(),
      deleteMany: jest.fn()
    },
    entryTag: {
      findUnique: jest.fn(),
      findMany: jest.fn(),
      create: jest.fn(),
      update: jest.fn(),
      delete: jest.fn(),
      deleteMany: jest.fn()
    },
    entry: {
      findFirst: jest.fn()
    }
  };
  return {
    PrismaClient: jest.fn(() => mockPrismaClient),
    TagCategory: {
      EMOTION: 'EMOTION',
      PERSON: 'PERSON',
      PLACE: 'PLACE',
      TOPIC: 'TOPIC',
      KEYWORD: 'KEYWORD',
      ACTIVITY: 'ACTIVITY',
      EVENT: 'EVENT',
      ORGANIZATION: 'ORGANIZATION'
    }
  };
});

describe('TagService', () => {
  let tagService: TagService;
  let prisma: PrismaClient;

  beforeEach(() => {
    prisma = new PrismaClient();
    tagService = new TagService(prisma);
    jest.clearAllMocks();
  });

  describe('createTag', () => {
    it('should create a new tag', async () => {
      const mockTag: Tag = {
        id: 'tag-1',
        name: 'javascript',
        color: '#FFEAA7',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      (prisma.tag.findUnique as jest.Mock).mockResolvedValue(null);
      (prisma.tag.create as jest.Mock).mockResolvedValue(mockTag);

      const result = await tagService.createTag({
        name: 'JavaScript',
        userId: 'user-1',
        category: TagCategory.KEYWORD
      });

      expect(result).toEqual(mockTag);
      expect(prisma.tag.create).toHaveBeenCalledWith({
        data: {
          name: 'javascript',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          color: '#FFEAA7'
        }
      });
    });

    it('should return existing tag if it already exists', async () => {
      const mockTag: Tag = {
        id: 'tag-1',
        name: 'javascript',
        color: '#FFEAA7',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      (prisma.tag.findUnique as jest.Mock).mockResolvedValue(mockTag);

      const result = await tagService.createTag({
        name: 'JavaScript',
        userId: 'user-1'
      });

      expect(result).toEqual(mockTag);
      expect(prisma.tag.create).not.toHaveBeenCalled();
    });

    it('should generate appropriate color for category', async () => {
      (prisma.tag.findUnique as jest.Mock).mockResolvedValue(null);
      (prisma.tag.create as jest.Mock).mockImplementation(({ data }) => 
        Promise.resolve({ ...data, id: 'tag-1', createdAt: new Date() })
      );

      const result = await tagService.createTag({
        name: 'happy',
        userId: 'user-1',
        category: TagCategory.EMOTION
      });

      expect(prisma.tag.create).toHaveBeenCalledWith({
        data: expect.objectContaining({
          color: '#FF6B6B' // Color for EMOTION category
        })
      });
    });
  });

  describe('getOrCreateTags', () => {
    it('should return existing and create new tags', async () => {
      const existingTag: Tag = {
        id: 'tag-1',
        name: 'existing',
        color: '#000000',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      (prisma.tag.findMany as jest.Mock).mockResolvedValue([existingTag]);
      (prisma.tag.create as jest.Mock).mockImplementation(({ data }) => 
        Promise.resolve({ ...data, id: `tag-${Date.now()}`, createdAt: new Date() })
      );

      const result = await tagService.getOrCreateTags(
        ['existing', 'new1', 'new2'],
        'user-1',
        TagCategory.KEYWORD
      );

      expect(result.length).toBe(3);
      expect(result[0]).toEqual(existingTag);
      expect(prisma.tag.create).toHaveBeenCalledTimes(2);
    });
  });

  describe('attachTagsToEntry', () => {
    it('should attach tags to entry', async () => {
      const mockTag: Tag = {
        id: 'tag-1',
        name: 'javascript',
        color: '#FFEAA7',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      const mockEntryTag: EntryTag = {
        id: 'entry-tag-1',
        entryId: 'entry-1',
        tagId: 'tag-1',
        confidence: 0.9,
        autoGenerated: false,
        createdAt: new Date()
      };

      (prisma.tag.findUnique as jest.Mock).mockResolvedValue(null);
      (prisma.tag.create as jest.Mock).mockResolvedValue(mockTag);
      (prisma.entryTag.findUnique as jest.Mock).mockResolvedValue(null);
      (prisma.entryTag.create as jest.Mock).mockResolvedValue(mockEntryTag);

      const result = await tagService.attachTagsToEntry({
        entryId: 'entry-1',
        userId: 'user-1',
        tags: [
          { name: 'JavaScript', confidence: 0.9 }
        ]
      });

      expect(result.length).toBe(1);
      expect(result[0]).toEqual(mockEntryTag);
      expect(prisma.entryTag.create).toHaveBeenCalled();
    });

    it('should update confidence if tag already attached', async () => {
      const existingEntryTag: EntryTag = {
        id: 'entry-tag-1',
        entryId: 'entry-1',
        tagId: 'tag-1',
        confidence: 0.5,
        autoGenerated: false,
        createdAt: new Date()
      };

      const updatedEntryTag: EntryTag = {
        ...existingEntryTag,
        confidence: 0.9
      };

      (prisma.entryTag.findUnique as jest.Mock).mockResolvedValue(existingEntryTag);
      (prisma.entryTag.update as jest.Mock).mockResolvedValue(updatedEntryTag);

      const result = await tagService.attachTagsToEntry({
        entryId: 'entry-1',
        userId: 'user-1',
        tags: [
          { tagId: 'tag-1', confidence: 0.9 }
        ]
      });

      expect(result[0].confidence).toBe(0.9);
      expect(prisma.entryTag.update).toHaveBeenCalled();
    });
  });

  describe('removeTagsFromEntry', () => {
    it('should remove tags from entry', async () => {
      (prisma.entryTag.deleteMany as jest.Mock).mockResolvedValue({ count: 2 });

      await tagService.removeTagsFromEntry('entry-1', ['tag-1', 'tag-2']);

      expect(prisma.entryTag.deleteMany).toHaveBeenCalledWith({
        where: {
          entryId: 'entry-1',
          tagId: {
            in: ['tag-1', 'tag-2']
          }
        }
      });
    });
  });

  describe('getUserTags', () => {
    it('should get user tags with stats', async () => {
      const mockTags = [
        {
          id: 'tag-1',
          name: 'javascript',
          color: '#FFEAA7',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date(),
          entries: [
            { entry: { createdAt: new Date('2024-01-01') } },
            { entry: { createdAt: new Date('2024-01-02') } }
          ]
        }
      ];

      (prisma.tag.findMany as jest.Mock).mockResolvedValue(mockTags);

      const result = await tagService.getUserTags('user-1', {
        sortBy: 'usage',
        limit: 10
      });

      expect(result.length).toBe(1);
      expect(result[0].usageCount).toBe(2);
      expect(result[0].lastUsed).toEqual(new Date('2024-01-02'));
    });

    it('should filter by category', async () => {
      (prisma.tag.findMany as jest.Mock).mockResolvedValue([]);

      await tagService.getUserTags('user-1', {
        category: TagCategory.EMOTION
      });

      expect(prisma.tag.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: {
            userId: 'user-1',
            category: TagCategory.EMOTION
          }
        })
      );
    });
  });

  describe('searchTags', () => {
    it('should search tags by name', async () => {
      const mockTags: Tag[] = [
        {
          id: 'tag-1',
          name: 'javascript',
          color: '#FFEAA7',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        }
      ];

      (prisma.tag.findMany as jest.Mock).mockResolvedValue(mockTags);

      const result = await tagService.searchTags('user-1', 'java', {
        limit: 5
      });

      expect(result).toEqual(mockTags);
      expect(prisma.tag.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: {
            userId: 'user-1',
            name: {
              contains: 'java',
              mode: 'insensitive'
            }
          },
          take: 5
        })
      );
    });
  });

  describe('updateTag', () => {
    it('should update tag', async () => {
      const mockTag: Tag = {
        id: 'tag-1',
        name: 'javascript',
        color: '#FFEAA7',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      const updatedTag: Tag = {
        ...mockTag,
        name: 'typescript',
        color: '#FF0000'
      };

      (prisma.tag.findFirst as jest.Mock).mockResolvedValue(mockTag);
      (prisma.tag.update as jest.Mock).mockResolvedValue(updatedTag);

      const result = await tagService.updateTag('tag-1', 'user-1', {
        name: 'TypeScript',
        color: '#FF0000'
      });

      expect(result).toEqual(updatedTag);
      expect(prisma.tag.update).toHaveBeenCalledWith({
        where: { id: 'tag-1' },
        data: {
          name: 'typescript',
          color: '#FF0000',
          category: undefined
        }
      });
    });

    it('should throw error if tag not found', async () => {
      (prisma.tag.findFirst as jest.Mock).mockResolvedValue(null);

      await expect(
        tagService.updateTag('tag-1', 'user-1', { name: 'new' })
      ).rejects.toThrow('Tag not found or access denied');
    });
  });

  describe('deleteTag', () => {
    it('should delete tag', async () => {
      const mockTag: Tag = {
        id: 'tag-1',
        name: 'javascript',
        color: '#FFEAA7',
        userId: 'user-1',
        category: TagCategory.KEYWORD,
        createdAt: new Date()
      };

      (prisma.tag.findFirst as jest.Mock).mockResolvedValue(mockTag);
      (prisma.tag.delete as jest.Mock).mockResolvedValue(mockTag);

      await tagService.deleteTag('tag-1', 'user-1');

      expect(prisma.tag.delete).toHaveBeenCalledWith({
        where: { id: 'tag-1' }
      });
    });
  });

  describe('mergeTags', () => {
    it('should merge multiple tags into one', async () => {
      const tags: Tag[] = [
        {
          id: 'tag-1',
          name: 'js',
          color: '#000',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        },
        {
          id: 'tag-2',
          name: 'javascript',
          color: '#111',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        },
        {
          id: 'tag-target',
          name: 'javascript',
          color: '#FFEAA7',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        }
      ];

      const entryTags: EntryTag[] = [
        {
          id: 'et-1',
          entryId: 'entry-1',
          tagId: 'tag-1',
          confidence: 1,
          autoGenerated: false,
          createdAt: new Date()
        },
        {
          id: 'et-2',
          entryId: 'entry-2',
          tagId: 'tag-2',
          confidence: 1,
          autoGenerated: false,
          createdAt: new Date()
        }
      ];

      (prisma.tag.findMany as jest.Mock).mockResolvedValue(tags);
      (prisma.entryTag.findMany as jest.Mock).mockResolvedValue(entryTags);
      (prisma.entryTag.findUnique as jest.Mock).mockResolvedValue(null);
      (prisma.entryTag.create as jest.Mock).mockResolvedValue({});
      (prisma.entryTag.delete as jest.Mock).mockResolvedValue({});
      (prisma.tag.deleteMany as jest.Mock).mockResolvedValue({ count: 2 });
      (prisma.tag.findUnique as jest.Mock).mockResolvedValue(tags[2]);

      const result = await tagService.mergeTags(
        ['tag-1', 'tag-2'],
        'tag-target',
        'user-1'
      );

      expect(result).toEqual(tags[2]);
      expect(prisma.entryTag.create).toHaveBeenCalledTimes(2);
      expect(prisma.tag.deleteMany).toHaveBeenCalled();
    });
  });

  describe('cleanupUnusedTags', () => {
    it('should delete unused tags', async () => {
      const unusedTags: Tag[] = [
        {
          id: 'tag-1',
          name: 'unused1',
          color: '#000',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        },
        {
          id: 'tag-2',
          name: 'unused2',
          color: '#111',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date()
        }
      ];

      (prisma.tag.findMany as jest.Mock).mockResolvedValue(unusedTags);
      (prisma.tag.deleteMany as jest.Mock).mockResolvedValue({ count: 2 });

      const count = await tagService.cleanupUnusedTags('user-1');

      expect(count).toBe(2);
      expect(prisma.tag.deleteMany).toHaveBeenCalledWith({
        where: {
          id: {
            in: ['tag-1', 'tag-2']
          }
        }
      });
    });
  });

  describe('getPopularTags', () => {
    it('should get popular tags within date range', async () => {
      const recentDate = new Date();
      const oldDate = new Date(Date.now() - 60 * 24 * 60 * 60 * 1000); // 60 days ago

      const mockTags = [
        {
          id: 'tag-1',
          name: 'popular',
          color: '#000',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date(),
          entries: [
            { entry: { createdAt: recentDate } },
            { entry: { createdAt: recentDate } },
            { entry: { createdAt: recentDate } }
          ]
        },
        {
          id: 'tag-2',
          name: 'less-popular',
          color: '#111',
          userId: 'user-1',
          category: TagCategory.KEYWORD,
          createdAt: new Date(),
          entries: [
            { entry: { createdAt: recentDate } }
          ]
        }
      ];

      (prisma.tag.findMany as jest.Mock).mockResolvedValue(mockTags);

      const result = await tagService.getPopularTags('user-1', {
        days: 30,
        limit: 10
      });

      expect(result.length).toBe(2);
      expect(result[0].name).toBe('popular');
      expect(result[0].usageCount).toBe(3);
    });
  });
});