import { PrismaClient, Tag, TagCategory, EntryTag, Prisma } from '@prisma/client';
import { TagWithConfidence } from './nlpService';

export interface TagWithStats extends Tag {
  usageCount: number;
  lastUsed?: Date;
}

export interface CreateTagInput {
  name: string;
  userId: string;
  category?: TagCategory;
  color?: string;
}

export interface AttachTagsInput {
  entryId: string;
  tags: Array<{
    tagId?: string;
    name?: string;
    category?: TagCategory;
    confidence?: number;
    autoGenerated?: boolean;
  }>;
  userId: string;
}

export class TagService {
  private prisma: PrismaClient;

  constructor(prisma: PrismaClient) {
    this.prisma = prisma;
  }

  /**
   * Create a new tag
   */
  async createTag(input: CreateTagInput): Promise<Tag> {
    const { name, userId, category = TagCategory.KEYWORD, color } = input;
    
    // Check if tag already exists for user
    const existing = await this.prisma.tag.findUnique({
      where: {
        name_userId: {
          name: name.toLowerCase().trim(),
          userId
        }
      }
    });
    
    if (existing) {
      return existing;
    }
    
    // Create new tag
    return await this.prisma.tag.create({
      data: {
        name: name.toLowerCase().trim(),
        userId,
        category,
        color: color || this.generateColorForCategory(category)
      }
    });
  }

  /**
   * Create multiple tags
   */
  async createTags(tags: CreateTagInput[]): Promise<Tag[]> {
    const createdTags: Tag[] = [];
    
    for (const tagInput of tags) {
      const tag = await this.createTag(tagInput);
      createdTags.push(tag);
    }
    
    return createdTags;
  }

  /**
   * Get or create tags from names
   */
  async getOrCreateTags(
    names: string[], 
    userId: string, 
    category: TagCategory = TagCategory.KEYWORD
  ): Promise<Tag[]> {
    const normalizedNames = names.map(name => name.toLowerCase().trim());
    
    // Find existing tags
    const existingTags = await this.prisma.tag.findMany({
      where: {
        userId,
        name: {
          in: normalizedNames
        }
      }
    });
    
    const existingNames = existingTags.map(tag => tag.name);
    const newNames = normalizedNames.filter(name => !existingNames.includes(name));
    
    // Create new tags
    const newTags: Tag[] = [];
    for (const name of newNames) {
      const tag = await this.prisma.tag.create({
        data: {
          name,
          userId,
          category,
          color: this.generateColorForCategory(category)
        }
      });
      newTags.push(tag);
    }
    
    return [...existingTags, ...newTags];
  }

  /**
   * Attach tags to an entry
   */
  async attachTagsToEntry(input: AttachTagsInput): Promise<EntryTag[]> {
    const { entryId, tags, userId } = input;
    const entryTags: EntryTag[] = [];
    
    for (const tagInput of tags) {
      let tagId: string;
      
      if (tagInput.tagId) {
        tagId = tagInput.tagId;
      } else if (tagInput.name) {
        // Create or get tag by name
        const tag = await this.createTag({
          name: tagInput.name,
          userId,
          category: tagInput.category || TagCategory.KEYWORD
        });
        tagId = tag.id;
      } else {
        continue;
      }
      
      // Check if entry-tag relationship already exists
      const existing = await this.prisma.entryTag.findUnique({
        where: {
          entryId_tagId: {
            entryId,
            tagId
          }
        }
      });
      
      if (!existing) {
        const entryTag = await this.prisma.entryTag.create({
          data: {
            entryId,
            tagId,
            confidence: tagInput.confidence || 1.0,
            autoGenerated: tagInput.autoGenerated || false
          }
        });
        entryTags.push(entryTag);
      } else {
        // Update confidence if provided
        if (tagInput.confidence !== undefined) {
          const updated = await this.prisma.entryTag.update({
            where: { id: existing.id },
            data: { confidence: tagInput.confidence }
          });
          entryTags.push(updated);
        } else {
          entryTags.push(existing);
        }
      }
    }
    
    return entryTags;
  }

  /**
   * Remove tags from an entry
   */
  async removeTagsFromEntry(entryId: string, tagIds: string[]): Promise<void> {
    await this.prisma.entryTag.deleteMany({
      where: {
        entryId,
        tagId: {
          in: tagIds
        }
      }
    });
  }

  /**
   * Get tags for an entry
   */
  async getEntryTags(entryId: string): Promise<Array<Tag & { confidence: number; autoGenerated: boolean }>> {
    const entryTags = await this.prisma.entryTag.findMany({
      where: { entryId },
      include: { tag: true }
    });
    
    return entryTags.map(et => ({
      ...et.tag,
      confidence: et.confidence,
      autoGenerated: et.autoGenerated
    }));
  }

  /**
   * Get user's tags with usage statistics
   */
  async getUserTags(
    userId: string, 
    options?: {
      category?: TagCategory;
      sortBy?: 'name' | 'usage' | 'created' | 'lastUsed';
      limit?: number;
      offset?: number;
    }
  ): Promise<TagWithStats[]> {
    const { category, sortBy = 'usage', limit = 100, offset = 0 } = options || {};
    
    const where: Prisma.TagWhereInput = { userId };
    if (category) {
      where.category = category;
    }
    
    const tags = await this.prisma.tag.findMany({
      where,
      include: {
        entries: {
          include: {
            entry: {
              select: {
                createdAt: true
              }
            }
          }
        }
      },
      take: limit,
      skip: offset
    });
    
    const tagsWithStats: TagWithStats[] = tags.map(tag => {
      const lastEntry = tag.entries
        .map(e => e.entry.createdAt)
        .sort((a, b) => b.getTime() - a.getTime())[0];
      
      return {
        ...tag,
        usageCount: tag.entries.length,
        lastUsed: lastEntry,
        entries: undefined as any // Remove entries from response
      };
    });
    
    // Sort based on preference
    switch (sortBy) {
      case 'name':
        tagsWithStats.sort((a, b) => a.name.localeCompare(b.name));
        break;
      case 'usage':
        tagsWithStats.sort((a, b) => b.usageCount - a.usageCount);
        break;
      case 'created':
        tagsWithStats.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
        break;
      case 'lastUsed':
        tagsWithStats.sort((a, b) => {
          if (!a.lastUsed) return 1;
          if (!b.lastUsed) return -1;
          return b.lastUsed.getTime() - a.lastUsed.getTime();
        });
        break;
    }
    
    return tagsWithStats;
  }

  /**
   * Search tags by name
   */
  async searchTags(
    userId: string, 
    query: string, 
    options?: {
      category?: TagCategory;
      limit?: number;
    }
  ): Promise<Tag[]> {
    const { category, limit = 10 } = options || {};
    
    const where: Prisma.TagWhereInput = {
      userId,
      name: {
        contains: query.toLowerCase(),
        mode: 'insensitive'
      }
    };
    
    if (category) {
      where.category = category;
    }
    
    return await this.prisma.tag.findMany({
      where,
      take: limit,
      orderBy: {
        name: 'asc'
      }
    });
  }

  /**
   * Get tag suggestions based on existing tags
   */
  async getTagSuggestions(
    userId: string, 
    text: string, 
    limit: number = 5
  ): Promise<Tag[]> {
    const words = text.toLowerCase().split(/\s+/);
    const lastWord = words[words.length - 1];
    
    if (!lastWord || lastWord.length < 2) {
      return [];
    }
    
    return await this.prisma.tag.findMany({
      where: {
        userId,
        name: {
          startsWith: lastWord,
          mode: 'insensitive'
        }
      },
      take: limit,
      orderBy: {
        name: 'asc'
      }
    });
  }

  /**
   * Get popular tags (most used)
   */
  async getPopularTags(
    userId: string, 
    options?: {
      category?: TagCategory;
      days?: number;
      limit?: number;
    }
  ): Promise<TagWithStats[]> {
    const { category, days = 30, limit = 10 } = options || {};
    
    const dateFilter = new Date();
    dateFilter.setDate(dateFilter.getDate() - days);
    
    const where: Prisma.TagWhereInput = { userId };
    if (category) {
      where.category = category;
    }
    
    const tags = await this.prisma.tag.findMany({
      where,
      include: {
        entries: {
          where: {
            entry: {
              createdAt: {
                gte: dateFilter
              }
            }
          },
          include: {
            entry: {
              select: {
                createdAt: true
              }
            }
          }
        }
      }
    });
    
    const tagsWithStats: TagWithStats[] = tags
      .map(tag => {
        const lastEntry = tag.entries
          .map(e => e.entry.createdAt)
          .sort((a, b) => b.getTime() - a.getTime())[0];
        
        return {
          ...tag,
          usageCount: tag.entries.length,
          lastUsed: lastEntry,
          entries: undefined as any
        };
      })
      .filter(tag => tag.usageCount > 0)
      .sort((a, b) => b.usageCount - a.usageCount)
      .slice(0, limit);
    
    return tagsWithStats;
  }

  /**
   * Update tag
   */
  async updateTag(
    tagId: string, 
    userId: string, 
    data: {
      name?: string;
      color?: string;
      category?: TagCategory;
    }
  ): Promise<Tag> {
    // Verify ownership
    const tag = await this.prisma.tag.findFirst({
      where: {
        id: tagId,
        userId
      }
    });
    
    if (!tag) {
      throw new Error('Tag not found or access denied');
    }
    
    return await this.prisma.tag.update({
      where: { id: tagId },
      data: {
        name: data.name?.toLowerCase().trim(),
        color: data.color,
        category: data.category
      }
    });
  }

  /**
   * Delete tag
   */
  async deleteTag(tagId: string, userId: string): Promise<void> {
    // Verify ownership
    const tag = await this.prisma.tag.findFirst({
      where: {
        id: tagId,
        userId
      }
    });
    
    if (!tag) {
      throw new Error('Tag not found or access denied');
    }
    
    await this.prisma.tag.delete({
      where: { id: tagId }
    });
  }

  /**
   * Merge tags
   */
  async mergeTags(
    sourceTagIds: string[], 
    targetTagId: string, 
    userId: string
  ): Promise<Tag> {
    // Verify ownership of all tags
    const tags = await this.prisma.tag.findMany({
      where: {
        id: {
          in: [...sourceTagIds, targetTagId]
        },
        userId
      }
    });
    
    if (tags.length !== sourceTagIds.length + 1) {
      throw new Error('Some tags not found or access denied');
    }
    
    // Get all entry associations for source tags
    const entryTags = await this.prisma.entryTag.findMany({
      where: {
        tagId: {
          in: sourceTagIds
        }
      }
    });
    
    // Update associations to target tag
    for (const entryTag of entryTags) {
      // Check if target tag is already associated with this entry
      const existing = await this.prisma.entryTag.findUnique({
        where: {
          entryId_tagId: {
            entryId: entryTag.entryId,
            tagId: targetTagId
          }
        }
      });
      
      if (!existing) {
        // Create new association
        await this.prisma.entryTag.create({
          data: {
            entryId: entryTag.entryId,
            tagId: targetTagId,
            confidence: entryTag.confidence,
            autoGenerated: entryTag.autoGenerated
          }
        });
      }
      
      // Delete old association
      await this.prisma.entryTag.delete({
        where: { id: entryTag.id }
      });
    }
    
    // Delete source tags
    await this.prisma.tag.deleteMany({
      where: {
        id: {
          in: sourceTagIds
        }
      }
    });
    
    // Return target tag
    return await this.prisma.tag.findUnique({
      where: { id: targetTagId }
    }) as Tag;
  }

  /**
   * Generate color for tag category
   */
  private generateColorForCategory(category: TagCategory): string {
    const colors: Record<TagCategory, string> = {
      [TagCategory.EMOTION]: '#FF6B6B',
      [TagCategory.PERSON]: '#4ECDC4',
      [TagCategory.PLACE]: '#45B7D1',
      [TagCategory.TOPIC]: '#96CEB4',
      [TagCategory.KEYWORD]: '#FFEAA7',
      [TagCategory.ACTIVITY]: '#DDA0DD',
      [TagCategory.EVENT]: '#98D8C8',
      [TagCategory.ORGANIZATION]: '#F7DC6F'
    };
    
    return colors[category] || '#95A5A6';
  }

  /**
   * Clean up unused tags
   */
  async cleanupUnusedTags(userId: string): Promise<number> {
    // Find tags with no entries
    const unusedTags = await this.prisma.tag.findMany({
      where: {
        userId,
        entries: {
          none: {}
        }
      }
    });
    
    // Delete unused tags
    const result = await this.prisma.tag.deleteMany({
      where: {
        id: {
          in: unusedTags.map(tag => tag.id)
        }
      }
    });
    
    return result.count;
  }
}

export default TagService;