import { Request, Response } from 'express';
import { PrismaClient, Mood, Privacy } from '@prisma/client';
import { validationResult } from 'express-validator';

const prisma = new PrismaClient();

interface CreateEntryRequest {
  title?: string;
  content: string;
  mood?: Mood;
  privacy?: Privacy;
  location?: string;
  weather?: string;
  tags?: string[];
  isFavorite?: boolean;
}

interface UpdateEntryRequest extends Partial<CreateEntryRequest> {}

interface QueryParams {
  page?: string;
  limit?: string;
  search?: string;
  mood?: Mood;
  startDate?: string;
  endDate?: string;
  tags?: string;
  isFavorite?: string;
  sortBy?: 'createdAt' | 'updatedAt' | 'title';
  sortOrder?: 'asc' | 'desc';
}

// Create a new entry
export const createEntry = async (req: Request<{}, {}, CreateEntryRequest>, res: Response) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { title, content, mood, privacy, location, weather, tags, isFavorite } = req.body;

    // Calculate word count
    const wordCount = content.trim().split(/\s+/).length;

    // Start a transaction to create entry and tags
    const entry = await prisma.$transaction(async (tx) => {
      // Create the entry
      const newEntry = await tx.entry.create({
        data: {
          userId: req.user!.id,
          title,
          content,
          mood,
          privacy: privacy || Privacy.PRIVATE,
          location,
          weather,
          wordCount,
          isFavorite: isFavorite || false,
        },
        include: {
          tags: {
            include: {
              tag: true
            }
          },
          attachments: true,
        }
      });

      // Process tags if provided
      if (tags && tags.length > 0) {
        for (const tagName of tags) {
          // Find or create tag
          let tag = await tx.tag.findFirst({
            where: {
              name: tagName.toLowerCase(),
              userId: req.user!.id
            }
          });

          if (!tag) {
            tag = await tx.tag.create({
              data: {
                name: tagName.toLowerCase(),
                userId: req.user!.id,
                category: 'KEYWORD'
              }
            });
          }

          // Link tag to entry
          await tx.entryTag.create({
            data: {
              entryId: newEntry.id,
              tagId: tag.id,
              confidence: 1.0,
              autoGenerated: false
            }
          });
        }

        // Fetch the entry with tags
        return await tx.entry.findUnique({
          where: { id: newEntry.id },
          include: {
            tags: {
              include: {
                tag: true
              }
            },
            attachments: true,
          }
        });
      }

      return newEntry;
    });

    res.status(201).json({
      message: 'Entry created successfully',
      entry
    });
  } catch (error) {
    console.error('Create entry error:', error);
    res.status(500).json({ error: 'Failed to create entry' });
  }
};

// Get all entries for the authenticated user
export const getEntries = async (req: Request<{}, {}, {}, QueryParams>, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const {
      page = '1',
      limit = '10',
      search,
      mood,
      startDate,
      endDate,
      tags,
      isFavorite,
      sortBy = 'createdAt',
      sortOrder = 'desc'
    } = req.query;

    const pageNum = parseInt(page);
    const limitNum = parseInt(limit);
    const skip = (pageNum - 1) * limitNum;

    // Build where clause
    const where: any = {
      userId: req.user.id
    };

    // Add search filter
    if (search) {
      where.OR = [
        { title: { contains: search, mode: 'insensitive' } },
        { content: { contains: search, mode: 'insensitive' } }
      ];
    }

    // Add mood filter
    if (mood) {
      where.mood = mood;
    }

    // Add date range filter
    if (startDate || endDate) {
      where.createdAt = {};
      if (startDate) {
        where.createdAt.gte = new Date(startDate);
      }
      if (endDate) {
        where.createdAt.lte = new Date(endDate);
      }
    }

    // Add favorite filter
    if (isFavorite === 'true') {
      where.isFavorite = true;
    }

    // Add tags filter
    if (tags) {
      const tagArray = tags.split(',').map(t => t.trim().toLowerCase());
      where.tags = {
        some: {
          tag: {
            name: {
              in: tagArray
            }
          }
        }
      };
    }

    // Get total count
    const totalCount = await prisma.entry.count({ where });

    // Get entries
    const entries = await prisma.entry.findMany({
      where,
      skip,
      take: limitNum,
      orderBy: {
        [sortBy]: sortOrder
      },
      include: {
        tags: {
          include: {
            tag: true
          }
        },
        attachments: true,
        _count: {
          select: {
            attachments: true,
            tags: true
          }
        }
      }
    });

    res.json({
      entries,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total: totalCount,
        totalPages: Math.ceil(totalCount / limitNum)
      }
    });
  } catch (error) {
    console.error('Get entries error:', error);
    res.status(500).json({ error: 'Failed to fetch entries' });
  }
};

// Get a single entry
export const getEntry = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { id } = req.params;

    const entry = await prisma.entry.findFirst({
      where: {
        id,
        userId: req.user.id
      },
      include: {
        tags: {
          include: {
            tag: true
          }
        },
        attachments: true,
        user: {
          select: {
            id: true,
            username: true,
            avatar: true
          }
        }
      }
    });

    if (!entry) {
      return res.status(404).json({ error: 'Entry not found' });
    }

    res.json({ entry });
  } catch (error) {
    console.error('Get entry error:', error);
    res.status(500).json({ error: 'Failed to fetch entry' });
  }
};

// Update an entry
export const updateEntry = async (req: Request<{ id: string }, {}, UpdateEntryRequest>, res: Response) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }

    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { id } = req.params;
    const { title, content, mood, privacy, location, weather, tags, isFavorite } = req.body;

    // Check if entry exists and belongs to user
    const existingEntry = await prisma.entry.findFirst({
      where: {
        id,
        userId: req.user.id
      }
    });

    if (!existingEntry) {
      return res.status(404).json({ error: 'Entry not found' });
    }

    // Calculate word count if content is being updated
    const wordCount = content ? content.trim().split(/\s+/).length : existingEntry.wordCount;

    // Update entry in a transaction
    const updatedEntry = await prisma.$transaction(async (tx) => {
      // Update the entry
      const entry = await tx.entry.update({
        where: { id },
        data: {
          title,
          content,
          mood,
          privacy,
          location,
          weather,
          wordCount,
          isFavorite
        }
      });

      // Update tags if provided
      if (tags !== undefined) {
        // Remove all existing tags
        await tx.entryTag.deleteMany({
          where: { entryId: id }
        });

        // Add new tags
        if (tags.length > 0) {
          for (const tagName of tags) {
            // Find or create tag
            let tag = await tx.tag.findFirst({
              where: {
                name: tagName.toLowerCase(),
                userId: req.user!.id
              }
            });

            if (!tag) {
              tag = await tx.tag.create({
                data: {
                  name: tagName.toLowerCase(),
                  userId: req.user!.id,
                  category: 'KEYWORD'
                }
              });
            }

            // Link tag to entry
            await tx.entryTag.create({
              data: {
                entryId: entry.id,
                tagId: tag.id,
                confidence: 1.0,
                autoGenerated: false
              }
            });
          }
        }
      }

      // Return updated entry with relations
      return await tx.entry.findUnique({
        where: { id },
        include: {
          tags: {
            include: {
              tag: true
            }
          },
          attachments: true
        }
      });
    });

    res.json({
      message: 'Entry updated successfully',
      entry: updatedEntry
    });
  } catch (error) {
    console.error('Update entry error:', error);
    res.status(500).json({ error: 'Failed to update entry' });
  }
};

// Delete an entry
export const deleteEntry = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { id } = req.params;

    // Check if entry exists and belongs to user
    const entry = await prisma.entry.findFirst({
      where: {
        id,
        userId: req.user.id
      },
      include: {
        attachments: true
      }
    });

    if (!entry) {
      return res.status(404).json({ error: 'Entry not found' });
    }

    // Delete entry (cascades to tags and attachments)
    await prisma.entry.delete({
      where: { id }
    });

    // TODO: Delete attachment files from storage

    res.json({ message: 'Entry deleted successfully' });
  } catch (error) {
    console.error('Delete entry error:', error);
    res.status(500).json({ error: 'Failed to delete entry' });
  }
};

// Toggle favorite status
export const toggleFavorite = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { id } = req.params;

    // Check if entry exists and belongs to user
    const entry = await prisma.entry.findFirst({
      where: {
        id,
        userId: req.user.id
      }
    });

    if (!entry) {
      return res.status(404).json({ error: 'Entry not found' });
    }

    // Toggle favorite status
    const updatedEntry = await prisma.entry.update({
      where: { id },
      data: {
        isFavorite: !entry.isFavorite
      }
    });

    res.json({
      message: `Entry ${updatedEntry.isFavorite ? 'added to' : 'removed from'} favorites`,
      isFavorite: updatedEntry.isFavorite
    });
  } catch (error) {
    console.error('Toggle favorite error:', error);
    res.status(500).json({ error: 'Failed to toggle favorite status' });
  }
};

// Search entries with full-text search
export const searchEntries = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { q, page = '1', limit = '10' } = req.query;

    if (!q || typeof q !== 'string') {
      return res.status(400).json({ error: 'Search query is required' });
    }

    const pageNum = parseInt(page as string);
    const limitNum = parseInt(limit as string);
    const skip = (pageNum - 1) * limitNum;

    // Use PostgreSQL full-text search if available
    // For now, using simple contains search
    const where = {
      userId: req.user.id,
      OR: [
        { title: { contains: q, mode: 'insensitive' as const } },
        { content: { contains: q, mode: 'insensitive' as const } },
        {
          tags: {
            some: {
              tag: {
                name: { contains: q.toLowerCase(), mode: 'insensitive' as const }
              }
            }
          }
        }
      ]
    };

    const totalCount = await prisma.entry.count({ where });

    const entries = await prisma.entry.findMany({
      where,
      skip,
      take: limitNum,
      orderBy: {
        createdAt: 'desc'
      },
      include: {
        tags: {
          include: {
            tag: true
          }
        },
        attachments: true
      }
    });

    res.json({
      entries,
      query: q,
      pagination: {
        page: pageNum,
        limit: limitNum,
        total: totalCount,
        totalPages: Math.ceil(totalCount / limitNum)
      }
    });
  } catch (error) {
    console.error('Search entries error:', error);
    res.status(500).json({ error: 'Failed to search entries' });
  }
};

// Get entry statistics
export const getEntryStats = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    const { startDate, endDate } = req.query;

    const where: any = {
      userId: req.user.id
    };

    if (startDate || endDate) {
      where.createdAt = {};
      if (startDate) {
        where.createdAt.gte = new Date(startDate as string);
      }
      if (endDate) {
        where.createdAt.lte = new Date(endDate as string);
      }
    }

    // Get various statistics
    const [
      totalEntries,
      totalWords,
      moodCounts,
      favoriteCount,
      entriesByDay,
      topTags
    ] = await Promise.all([
      // Total entries
      prisma.entry.count({ where }),
      
      // Total words
      prisma.entry.aggregate({
        where,
        _sum: { wordCount: true }
      }),
      
      // Mood distribution
      prisma.entry.groupBy({
        by: ['mood'],
        where,
        _count: true
      }),
      
      // Favorite count
      prisma.entry.count({
        where: { ...where, isFavorite: true }
      }),
      
      // Entries by day (last 30 days)
      prisma.$queryRaw`
        SELECT DATE(created_at) as date, COUNT(*) as count
        FROM "Entry"
        WHERE user_id = ${req.user.id}
          AND created_at >= NOW() - INTERVAL '30 days'
        GROUP BY DATE(created_at)
        ORDER BY date DESC
      `,
      
      // Top tags
      prisma.$queryRaw`
        SELECT t.name, t.id, COUNT(et.id) as usage_count
        FROM "Tag" t
        JOIN "EntryTag" et ON t.id = et.tag_id
        WHERE t.user_id = ${req.user.id}
        GROUP BY t.id, t.name
        ORDER BY usage_count DESC
        LIMIT 10
      `
    ]);

    res.json({
      stats: {
        totalEntries,
        totalWords: totalWords._sum.wordCount || 0,
        averageWords: totalEntries > 0 ? Math.round((totalWords._sum.wordCount || 0) / totalEntries) : 0,
        favoriteCount,
        moodDistribution: moodCounts,
        entriesByDay,
        topTags
      }
    });
  } catch (error) {
    console.error('Get entry stats error:', error);
    res.status(500).json({ error: 'Failed to fetch entry statistics' });
  }
};